// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: counter.proto

package com.hyf.jraft.counter.rpc;

public interface GetValueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetValueRequest)
    com.google.protobuf.MessageOrBuilder {
}
