// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: counter.proto

package com.hyf.jraft.counter.rpc;

public interface IncrementAndGetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IncrementAndGetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 count = 1;</code>
   * @return The count.
   */
  long getCount();
}
